version: 2
updates:
  - package-ecosystem: "npm"
    groups:
      all:
        patterns:
          - "*"
    directory: "/code"
    schedule:
      interval: "monthly"
    reviewers:
      - "Ushcode"


  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Ushcode"

      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Ushcode"
