#
# Compose file for the TWA-VP.
#
version: "3.8"

# All Services
services:
  # Empty visualisation image for deployment.
  visualise:
    image: ghcr.io/cambridge-cares/twa-vf:vis-platform-SNAPSHOT
    container_name: "twa-vis-platform"
    restart: "no"
    secrets:
      - mapbox_user
      - mapbox_api_key
    build:
      context: "./"
      dockerfile: "Dockerfile"
      target: prod
      labels:
        authors: "support@cmcl.io"
        description: "TWA Visualisation Platform image."
    volumes:
      - ./uploads/config:/twa/uploads/config
      - ./uploads/optional-pages:/twa/uploads/optional-pages
      - ./uploads/style-overrides.css:/twa/uploads/style-overrides.css
      - ./uploads/data:/twa/public/uploads/data
      - ./uploads/images:/twa/public/uploads/images
    ports:
      - "80:3000" 
secrets:
    mapbox_user: 
      file: ./mapbox_user
    mapbox_api_key:
      file: ./mapbox_api_key
