#
# Compose file for the TWA-VP.
#
services:
  # Empty visualisation image for deployment.
  base:
    image: ghcr.io/cambridge-cares/twa-vf
    container_name: "twa-vf"
    restart: "no"
    secrets:
      - mapbox_username
      - mapbox_api_key
    build:
      context: .
      dockerfile: "Dockerfile"
      target: prod
      labels:
        authors: "support@cmcl.io"
        description: "TWA Visualisation Platform image."
  
  latest:
    extends: base
    image: ghcr.io/cambridge-cares/twa-vf:latest

  semantic-snapshot:
      extends: base
      image: ghcr.io/cambridge-cares/twa-vf:${MAJOR}.${MINOR}.${PATCH}-${SNAPSHOT}

  major-snapshot:
    extends: base
    image: ghcr.io/cambridge-cares/twa-vf:${MAJOR}-${SNAPSHOT}

  snapshot:
    extends: base
    image: ghcr.io/cambridge-cares/twa-vf:${SNAPSHOT}

    volumes:
      - ./uploads:/twa/public/
    ports:
      - "80:3000" 
secrets:
    mapbox_username:
      file: ./mapbox_username
    mapbox_api_key:
      file: ./mapbox_api_key
