#
# Compose file for the TWA-VP.
#
services:
  # Empty visualisation image for deployment.
  visualise:
    image: ghcr.io/cambridge-cares/twa-vf:vis-platform-SNAPSHOT
    container_name: "twa-vis-platform"
    restart: "no"
    secrets:
      - mapbox_username
      - mapbox_api_key
    build:
      context: "./"
      dockerfile: "Dockerfile"
      target: prod
      labels:
        authors: "support@cmcl.io"
        description: "TWA Visualisation Platform image."
    volumes:
      - ./uploads:/twa/public/
    ports:
      - "80:3000" 
secrets:
    mapbox_username: 
      file: ./mapbox_username
    mapbox_api_key:
      file: ./mapbox_api_key
