name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
     types: [opened, ready_for_review]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: Ushcode
        numOfAssignee: 1

    - name: Auto assign reviewer
      uses: jagadish-k/auto-assign-reviewer@v1.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: Ushcode