name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - code/**
  pull_request:
    branches: ["main"]
    types: [closed]
    paths:
      - code/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set version variables from file
        id: read-version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR=$(echo $VERSION | cut -d. -f1).$(echo $VERSION | cut -d. -f2)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build docker image and push to ghcr
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/theworldavatar.io/viz:latest
            ghcr.io/theworldavatar.io/viz:${{ env.VERSION }}
            ghcr.io/theworldavatar.io/viz:${{ env.MAJOR }}
            ghcr.io/theworldavatar.io/viz:${{ env.MINOR }}

