name: Lint TypeScript code

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  cache-install-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Lint TypeScript code
        run: pnpm lint
