name: Lint TypeScript code

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  cache-install-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4 <- pinned commit for safety
        name: Install pnpm
        with:
          run_install: true
          package_json_file: code/package.json
          standalone: true

      # - uses: actions/setup-node@v4
      #   name: Setup Node.js
      #   with:
      #     node-version-file: code/package.json
      #     cache: "pnpm"

      - name: Lint TypeScript code
        run: pnpm lint
        working-directory: code
