name: Lint TypeScript code

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  cache-install-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}``

      - uses: pnpm/action-setup@a7487c7 #v4 <- pinned commit for safety
        name: Install pnpm
        with:
          version: 10
          run_install: true

      - name: Lint TypeScript code
        run: pnpm lint
        working-directory: code
